# Generated by Django 5.1.3 on 2024-11-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='managers',
            fields=[
                ('manager_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('password_hash', models.CharField(max_length=255)),
            ],
        ),
    ]
