# Generated by Django 5.1.3 on 2024-11-18 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('drivers', '0001_initial'),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(max_length=3)),
                ('transaction_time', models.DateField()),
                ('chassis_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.chassis')),
                ('container_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.containers')),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.drivers')),
                ('trailer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.trailers')),
                ('truck_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.trucks')),
                ('yard_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.yards')),
            ],
        ),
    ]
