# Generated by Django 5.1.3 on 2024-11-18 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('driver_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('password_hash', models.CharField(max_length=255)),
                ('division_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.divisions')),
            ],
        ),
    ]
