# Generated by Django 5.1.3 on 2024-12-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="drivers",
            name="state",
            field=models.CharField(default="off_work", max_length=10),
        ),
    ]
