# Generated by Django 5.1.3 on 2024-11-18 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Divisions',
            fields=[
                ('division_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Yards',
            fields=[
                ('yard_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('division_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.divisions')),
            ],
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('site_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(max_length=10)),
                ('yard_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.yards')),
            ],
        ),
    ]
