# Generated by Django 5.1.3 on 2024-11-28 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Divisions",
            fields=[
                (
                    "division_id",
                    models.CharField(max_length=4, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "divisions",
            },
        ),
        migrations.CreateModel(
            name="Sites",
            fields=[
                (
                    "site_id",
                    models.CharField(max_length=17, primary_key=True, serialize=False),
                ),
                ("asset_type", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "sites",
            },
        ),
        migrations.CreateModel(
            name="ParkingSlots",
            fields=[
                (
                    "slot_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("is_occupied", models.BooleanField(default=False)),
                (
                    "site_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="places.sites"
                    ),
                ),
            ],
            options={
                "db_table": "parking_slots",
            },
        ),
        migrations.CreateModel(
            name="Yards",
            fields=[
                (
                    "yard_id",
                    models.CharField(max_length=7, primary_key=True, serialize=False),
                ),
                (
                    "division_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="places.divisions",
                    ),
                ),
            ],
            options={
                "db_table": "yards",
            },
        ),
        migrations.AddField(
            model_name="sites",
            name="yard_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="places.yards"
            ),
        ),
    ]
