# Generated by Django 5.1.3 on 2024-11-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chassis",
            fields=[
                (
                    "chassis_id",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("type", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Containers",
            fields=[
                (
                    "container_id",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("type", models.CharField(max_length=10)),
                ("size", models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name="Trailers",
            fields=[
                (
                    "trailer_id",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("size", models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name="Trucks",
            fields=[
                (
                    "truck_id",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("type", models.CharField(max_length=10)),
            ],
        ),
    ]
