# Generated by Django 5.1.3 on 2024-11-28 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chassis",
            fields=[
                (
                    "chassis_id",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("type", models.CharField(max_length=10)),
                (
                    "parked_place",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="places.parkingslots",
                    ),
                ),
            ],
            options={
                "db_table": "chassis",
            },
        ),
        migrations.CreateModel(
            name="Containers",
            fields=[
                (
                    "container_id",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("type", models.CharField(max_length=10)),
                ("size", models.CharField(max_length=5)),
                (
                    "parked_place",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="places.parkingslots",
                    ),
                ),
            ],
            options={
                "db_table": "containers",
            },
        ),
        migrations.CreateModel(
            name="Trailers",
            fields=[
                (
                    "trailer_id",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("size", models.CharField(max_length=5)),
                (
                    "parked_place",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="places.parkingslots",
                    ),
                ),
            ],
            options={
                "db_table": "trailers",
            },
        ),
        migrations.CreateModel(
            name="Trucks",
            fields=[
                (
                    "truck_id",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("type", models.CharField(max_length=10)),
                (
                    "parked_place",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="places.parkingslots",
                    ),
                ),
            ],
            options={
                "db_table": "trucks",
            },
        ),
    ]
