# Generated by Django 5.1.3 on 2024-12-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0002_alter_chassis_chassis_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="containers",
            name="type",
        ),
        migrations.AddField(
            model_name="chassis",
            name="state",
            field=models.CharField(default="parked", max_length=10),
        ),
        migrations.AddField(
            model_name="containers",
            name="state",
            field=models.CharField(default="parked", max_length=10),
        ),
        migrations.AddField(
            model_name="trailers",
            name="state",
            field=models.CharField(default="parked", max_length=10),
        ),
        migrations.AddField(
            model_name="trailers",
            name="type",
            field=models.CharField(default="123", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trucks",
            name="state",
            field=models.CharField(default="parked", max_length=10),
        ),
    ]
