# Generated by Django 5.1.3 on 2024-12-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0003_remove_containers_type_chassis_state_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trailers",
            name="type",
        ),
        migrations.AddField(
            model_name="containers",
            name="type",
            field=models.CharField(default="Dry", max_length=10),
            preserve_default=False,
        ),
    ]
